[package]
edition = "2021"
name = "edgee"
version = "0.1.0"
authors = ["Edgee <opensource@edgee.cloud>"]
description = "The full-stack edge platform for your edge oriented applications"
keywords = ["Edgee"]
categories = ["wasm"]
license = "Apache-2.0"

[dependencies]
hyper = { version = "1", features = ["full"] }
tokio = { version = "1", features = ["full"] }
http-body-util = "0.1"
hyper-util = { version = "0.1", features = ["full"] }
bytes = "1.6.0"
http = "1.1.0"
clap = { version = "^4", features = ["derive"] }
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
simple_logger = "4.3"
log = "0.4"
miette = "7.2.0"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
