[package]
edition = "2021"
name = "edgee"
version = "0.1.2"
authors = ["Edgee <opensource@edgee.cloud>"]
description = "The full-stack edge platform for your edge oriented applications"
keywords = ["Edgee"]
categories = ["wasm"]
license = "Apache-2.0"
repository = "https://github.com/edgee-cloud/edgee"
homepage = "https://www.edgee.cloud"

[dependencies]
anyhow = "1.0.83"
bytes = "1.6.0"
clap = { version = "^4", features = ["derive"] }
http = "1.1.0"
http-body-util = "0.1"
hyper = { version = "1", features = ["full"] }
hyper-rustls = { version = "0.27.2", features = ["http2", "ring"] }
hyper-util = { version = "0.1.5", features = ["full"] }
libflate = "2.1.0"
log = "0.4"
rand = "0.8.5"
regex = "1.10.4"
rustls = { version = "0.23.5", features = ["ring"] }
rustls-pemfile = "2.1.2"
rustls-pki-types = "1.7.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
simple_logger = "4.3"
tokio = { version = "1", features = ["full"] }
tokio-rustls = { version = "0.26.0", features = ["ring"] }
toml = "0.8.12"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter", "json"] }
