[package]
edition = "2021"
name = "edgee"
version = "0.3.3"
authors = ["Edgee <opensource@edgee.cloud>"]
description = "The full-stack edge platform for your edge oriented applications"
keywords = ["Edgee"]
categories = ["wasm"]
license = "Apache-2.0"
repository = "https://github.com/edgee-cloud/edgee"
homepage = "https://www.edgee.cloud"

[dependencies]
addr = "0.15.6"
aes = "0.8.4"
anyhow = "1.0.83"
base64 = "0.22.1"
brotli = "6.0.0"
bytes = "1.6.0"
cbc = { version = "0.1.2", features = ["std"] }
chrono = { version = "0.4.38", features = ["serde"] }
cookie = "0.18.1"
hex = "0.4.3"
html-escape = "0.2.13"
http = "1.1.0"
http-body-util = "0.1"
hyper = { version = "1", features = ["full"] }
hyper-rustls = { version = "0.27.2", features = ["http2", "ring"] }
hyper-util = { version = "0.1.5", features = ["full"] }
ipnetwork = "0.20.0"
json_comments = "0.2.2"
libflate = "2.1.0"
log = "0.4"
openssl = "0.10"
rand = "0.8.5"
regex = "1.10.4"
reqwest = "0.12.5"
rustls = { version = "0.23.5", features = ["ring"] }
rustls-pemfile = "2.1.2"
rustls-pki-types = "1.7.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yml = "0.0.12"
tokio = { version = "1", features = ["full"] }
tokio-rustls = { version = "0.26.0", features = ["ring"] }
toml = "0.8.12"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter", "json"] }
url = "2.5.2"
uuid = { version = "1.9.1", features = ["v4", "serde"] }
wasmtime = "22.0.0"
wasmtime-wasi = "22.0.0"

[features]
bundled = [
    "openssl/vendored",
]
